=== iamxiatian/xml/experiments/code/E4-book.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="1.1">
    <xs:element name="book">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title"/>
                <xs:element name="price" type="xs:decimal"/>
                <xs:element ref="authors"/>
                <xs:element name="press" type="xs:string"/>
                <xs:element name="pages" type="xs:integer"/>
                <xs:element name="description" type="xs:string"/>
                <xs:element name="cover" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:ID"/>
            <xs:attribute name="isbn" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{3}\-\d\-\d{3}\-\d{5}\-\d"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="title">
        <xs:complexType mixed="true">
            <xs:attribute name="lang" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="authors">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="unbounded">
                <xs:element name="author" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== iamxiatian/xml/experiments/code/E4-book.xml
<?xml version="1.0" encoding="UTF-8"?>

<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="E4-book.xsd" isbn="978-7-115-28282-8" id="b2">
    <title lang="CHN">数学之美</title>
    <price>45.00</price>
    <authors>
        <author>吴军</author>
    </authors>
    <press>人民邮电出版社</press>
    <pages>304</pages>
    <description>读了“数学之美”，才发现大学时学的数学知识，比如马尔科夫链、矩阵计算，甚至余弦函数原来都如此亲切，并且栩栩如生，才发现自然语言和信息处理这么有趣，
        才真正明白“数学是科学的皇后”这句名言。</description>
    <cover>book-math.jpg</cover>
</book>
